
spring:

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/rpg?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none