server:
  port: 8080
spring:
  server:
    port: 8081

  datasource:
    platform: mysql
    url: jdbc:mysql://rpgdb1.mysql.database.azure.com/rpg?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: rpgadmin1@rpgdb1
    password: bryceyoung1!


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none